### ISSUE TITLE
next updat e ?

### ISSUE THREAD

**Issue by Dibsymodzz** [Quoorex/minecraft-server-eu-bot#5]
next updat e ?

**Comment by pim97** [comment]
You can also buy them from websites just Google it

**Comment by Quoorex** [comment]
I probably won't work on this program in the near future, because I don't really have a use for it. But since this is open-source you are free to fork the project and do whatever you want with it. 
If you really need a functioning bot and don't want to code you should look into buying one, as @pim97 suggested.

**Comment by Ralphaf** [comment]
Hello, I would really like to buy a working bot, but not sure how to reach out to @pim97 , because there is no info on his profile

**Comment by Quoorex** [comment]
@Ralphaf You really just have to search for it online. Maybe take a look at forums like MC Market or MCTrades.

GitHub is unfortunately not offering the possibility of sending direct messages to users.
